// ═══════════════════════════════════════════
// AI COUNCIL — Export Utilities
// ═══════════════════════════════════════════

export function copyToClipboard(text) {
  if (navigator.clipboard && navigator.clipboard.writeText) {
    return navigator.clipboard.writeText(text);
  }
  // Fallback
  const textarea = document.createElement('textarea');
  textarea.value = text;
  textarea.style.position = 'fixed';
  textarea.style.left = '-9999px';
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand('copy');
  document.body.removeChild(textarea);
  return Promise.resolve();
}

export function exportAsText(session) {
  const lines = [
    '═══════════════════════════════════════════',
    '  AI COUNCIL — Session Report',
    '═══════════════════════════════════════════',
    '',
    `Date: ${new Date(session.createdAt).toLocaleString()}`,
    `Idea: ${session.idea}`,
    '',
    '───────────────────────────────────────────',
    '',
  ];

  session.responses.forEach((r) => {
    lines.push(`${r.agent.emoji} ${r.agent.name} (${r.agent.role})`);
    lines.push('─'.repeat(40));
    // Strip markdown bold markers for plain text
    lines.push(r.message.replace(/\*\*/g, ''));
    lines.push('');
    lines.push('');
  });

  lines.push('═══════════════════════════════════════════');
  lines.push('  Generated by AI Council');
  lines.push('  https://aicouncil.app');
  lines.push('═══════════════════════════════════════════');

  const content = lines.join('\n');
  downloadFile(content, `ai-council-${session.id}.txt`, 'text/plain');
}

export function exportAsPDF(session) {
  const html = buildPDFHtml(session);
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}

function buildPDFHtml(session) {
  const agentColors = {
    cyan: '#00f0ff',
    violet: '#bf5af2',
    rose: '#ff375f',
    emerald: '#30d158',
    amber: '#ffd60a',
  };

  const responsesHtml = session.responses
    .map((r) => {
      const color = agentColors[r.agent.color] || '#00f0ff';
      const messageHtml = r.message
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\n/g, '<br>');

      return `
        <div style="margin-bottom:24px;padding:20px;border-left:4px solid ${color};background:rgba(255,255,255,0.03);border-radius:8px;">
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;">
            <span style="font-size:24px;">${r.agent.emoji}</span>
            <div>
              <div style="font-weight:700;color:${color};font-size:16px;">${r.agent.name}</div>
              <div style="font-size:12px;color:#888;">${r.agent.role}</div>
            </div>
          </div>
          <div style="font-size:14px;line-height:1.7;color:#ddd;">${messageHtml}</div>
        </div>
      `;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <title>AI Council — ${session.idea}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Outfit:wght@600;700;800&display=swap');
    body { font-family: 'Inter', sans-serif; background: #0a0a0f; color: #e4e4e7; padding: 40px; max-width: 800px; margin: 0 auto; }
    h1 { font-family: 'Outfit', sans-serif; color: #fff; font-size: 28px; margin-bottom: 8px; }
    .meta { color: #888; font-size: 13px; margin-bottom: 32px; }
    .idea { background: rgba(0,240,255,0.05); border: 1px solid rgba(0,240,255,0.2); padding: 16px 20px; border-radius: 12px; margin-bottom: 32px; font-size: 15px; }
    @media print { body { background: white; color: #222; } .idea { border-color: #ccc; } }
  </style>
</head>
<body>
  <h1>🏛️ AI Council Report</h1>
  <div class="meta">${new Date(session.createdAt).toLocaleString()}</div>
  <div class="idea"><strong>Idea:</strong> ${session.idea}</div>
  ${responsesHtml}
  <hr style="border-color:#333;margin:32px 0;">
  <div style="text-align:center;color:#666;font-size:12px;">Generated by AI Council — aicouncil.app</div>
</body>
</html>`;
}

// ── Helper ────────────────────────────────────

function downloadFile(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
